import type { MaterialKind, TemplateCategory } from './types.ts'

/** diecuttemplates.com (DCT) katalog kaydı — temel bıçak izi (varyasyonlar hariç). */
export interface DctEntry {
  /** DCT kimliği, ör. `becf-10301`. */
  id: string
  material: MaterialKind
  group: TemplateCategory
  ecma: string
  fefco: string
  /** DCT’de bu temel şablonun kaç etiket varyasyonu var (+N Variations). */
  variations: number
  /** DCT varsayılan ölçüleri (mm): a uzunluk, b genişlik, c yükseklik. */
  dims: { a?: number; b?: number; c?: number }
  /** DCT parametre adları (a, b, c, d4 toz kapağı, d5 yapıştırma payı, …). */
  options: string[]
  /** Kapak/dil/toz kapağı/askı gibi DCT etiketleri. */
  tags: string[]
  /** Ön panelde pencere var. */
  windows?: boolean
}

/**
 * DCT envanteri — 3 malzeme × 28 grup × 273 temel şablon
 * (2026-09-02 tarihinde diecuttemplates.com katalog sayfalarından derlendi).
 * Geometri buradan gelmez; her kayıt `dct-map.ts` ile kendi üretecimize bağlanır.
 */
export const DCT_INVENTORY: readonly DctEntry[] = [
  { id: 'becf-12901', material: 'carton', group: 'angled-boxes', ecma: 'C20.20.10.10', fefco: '', variations: 0, dims: {a:100,b:80,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h'], tags: [] },
  { id: 'becf-12902', material: 'carton', group: 'angled-boxes', ecma: 'C30.40.01.20', fefco: '', variations: 0, dims: {a:90,b:150}, options: ['a', 'b', 'd4', 'd5'], tags: [] },
  { id: 'becf-12903', material: 'carton', group: 'angled-boxes', ecma: '', fefco: '', variations: 1, dims: {a:80,b:80,c:100}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h'], tags: [] },
  { id: 'becf-12101', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'x', 'y', '_dip', '_kulak'], tags: [] },
  { id: 'becf-12102', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'x', 'y', '_dip', '_kulak'], tags: [] },
  { id: 'becf-12103', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'x', 'x1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-12104', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'x', 'x1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-12105', material: 'carton', group: 'carton-bags-pillows', ecma: 'F70.01.00.00.A', fefco: '', variations: 0, dims: {a:100,b:40,c:150}, options: ['a', 'b', 'c', 'd', 'd5', '_kulak'], tags: [] },
  { id: 'becf-12106', material: 'carton', group: 'carton-bags-pillows', ecma: 'F70.01.00.00.B', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd5', 'h', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12107', material: 'carton', group: 'carton-bags-pillows', ecma: 'F70.01.00.00.A', fefco: '', variations: 0, dims: {a:100,b:40,c:150}, options: ['a', 'b', 'c', 'd', 'd5', '_dil', '_kulak'], tags: [] },
  { id: 'becf-12108', material: 'carton', group: 'carton-bags-pillows', ecma: 'F70.01.00.00.B', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd5', 'h', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12109', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'x', 'y', '_dip', '_kulak'], tags: [] },
  { id: 'becf-1210a', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:160,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd5', 'e', 'r2', 'x', 'x1', 'y1'], tags: [] },
  { id: 'becf-1210b', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:150,b:60,c:170}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'e', 'r1', 'r2', 'r3', 'y1', 'y2', 'z1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-1210c', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:150,b:60,c:170}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'e', 'r1', 'y1', 'y2', 'z1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-1210d', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'x', 'x1', 'y', 'y1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-1210e', material: 'carton', group: 'carton-bags-pillows', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'x', 'x1', 'y', 'y1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-12c01', material: 'carton', group: 'envelopes', ecma: 'F60.92.00.00.11', fefco: '', variations: 0, dims: {a:152,b:152}, options: ['a', 'b', 'c', 'd4', 'd5', 'r', 'y1', 'y2', '_kulak'], tags: [] },
  { id: 'becf-12c02', material: 'carton', group: 'envelopes', ecma: 'F60.93.00.00', fefco: '', variations: 0, dims: {a:265,b:120}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r1', 'x1', 'y1', '_kulak'], tags: [] },
  { id: 'becf-12c03', material: 'carton', group: 'envelopes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:20,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12c04', material: 'carton', group: 'envelopes', ecma: 'F80.53.00.00', fefco: '', variations: 0, dims: {a:100,b:205}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f'], tags: [] },
  { id: 'becf-12c05', material: 'carton', group: 'envelopes', ecma: 'F60.93.00.00', fefco: '', variations: 0, dims: {a:320,b:240,c:20}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [], windows: true },
  { id: 'becf-12b01', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:155,b:115,c:5}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-12b02', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:155,b:115,c:5}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-12b04', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:270,b:180,c:5}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'x1', '_kulak'], tags: [] },
  { id: 'becf-12b05', material: 'carton', group: 'folders', ecma: 'E40.82.00.00', fefco: '', variations: 0, dims: {a:170,b:120,c:25}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'r1', 'r2', 'z1', '_dil'], tags: [] },
  { id: 'becf-12b06', material: 'carton', group: 'folders', ecma: 'F60.91.00.00', fefco: '', variations: 0, dims: {a:300,b:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'x1'], tags: [] },
  { id: 'becf-12b07', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:165,b:180}, options: ['a', 'b', 'c', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i', 'j', '_kulak'], tags: [] },
  { id: 'becf-12b08', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:165,b:180}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i', 'j', '_kulak'], tags: [] },
  { id: 'becf-12b09', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:165,b:180}, options: ['a', 'b', 'c', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i', 'j', '_kulak'], tags: [] },
  { id: 'becf-12b0a', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:165,b:180}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i', 'j', '_kulak'], tags: [] },
  { id: 'becf-12b0b', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:165,b:180}, options: ['a', 'b', 'c', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i', 'j', '_kulak'], tags: [] },
  { id: 'becf-12b0c', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:90,b:50,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-12b0d', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {a:130,b:75,c:95}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil'], tags: [] },
  { id: 'becf-12b0e', material: 'carton', group: 'folders', ecma: '', fefco: '', variations: 0, dims: {}, options: ['backbone', 'capacity', 'capax1', 'capax2', 'card', 'cardno', 'crd_lmx', 'crd_lmy', 'crd_lp', 'crd_lx', 'crd_ly', 'crd_rmx', 'crd_rmy', 'crd_rp', 'crd_rx', 'crd_ry', 'gf', 'gf2', 'gfy1', 'gfy2', 'gfy3', 'gfy4', 'gfyon', 'h', 'hz1', 'hz2', 'l', 'pcktno', 'pcktr1', 'pcktr2', 'pcktx1', 'pcktx2', 'pckty1', 'pckty2', 'pocket', 'v1', 'v2', 'w'], tags: [] },
  { id: 'becf-12001', material: 'carton', group: 'food-boxes', ecma: 'B15.06.00.53', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil'], tags: [], windows: true },
  { id: 'becf-12002', material: 'carton', group: 'food-boxes', ecma: 'B15.06.00.53.B', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil'], tags: [] },
  { id: 'becf-12003', material: 'carton', group: 'food-boxes', ecma: 'B14.10.00.00', fefco: '', variations: 0, dims: {a:200,b:150,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil', '_flap'], tags: [] },
  { id: 'becf-12004', material: 'carton', group: 'food-boxes', ecma: 'B14.10.00.51.B', fefco: '', variations: 0, dims: {a:200,b:150,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12005', material: 'carton', group: 'food-boxes', ecma: 'B49.10.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12006', material: 'carton', group: 'food-boxes', ecma: 'B40.10.84.00.84.A', fefco: '', variations: 0, dims: {a:180,b:80,c:50}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-12007', material: 'carton', group: 'food-boxes', ecma: 'B20.01.00.53', fefco: '', variations: 0, dims: {a:220,b:220,c:30}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'r', 'r1', '_flap'], tags: [] },
  { id: 'becf-12008', material: 'carton', group: 'food-boxes', ecma: 'B40.10.84.00.84.B', fefco: '', variations: 0, dims: {a:150,b:150,c:50}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-12009', material: 'carton', group: 'food-boxes', ecma: 'B49.10.00.00.B', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: [], windows: true },
  { id: 'becf-1200a', material: 'carton', group: 'food-boxes', ecma: 'B14.10.00.00.B', fefco: '', variations: 0, dims: {a:200,b:150,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: [], windows: true },
  { id: 'becf-1200b', material: 'carton', group: 'food-boxes', ecma: 'D10.20.05.53', fefco: '', variations: 0, dims: {a:160,b:70,c:190}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h', '_dil'], tags: [], windows: true },
  { id: 'becf-1200c', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:90,c:100}, options: ['a', 'b', 'c', 'd', 'v1', 'v2'], tags: [] },
  { id: 'becf-1200d', material: 'carton', group: 'food-boxes', ecma: 'B15.06.00.55', fefco: '', variations: 0, dims: {a:150,b:80,c:30}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [], windows: true },
  { id: 'becf-1200e', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:100,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_kulak'], tags: [] },
  { id: 'becf-1200f', material: 'carton', group: 'food-boxes', ecma: 'B49.10.00.00.B', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', '_dil', '_dip', '_flap', '_kulak'], tags: [], windows: true },
  { id: 'becf-12010', material: 'carton', group: 'food-boxes', ecma: 'B15.06.00.53C', fefco: '', variations: 0, dims: {a:150,b:95,c:100}, options: ['a', 'b', 'c', 'd4', 'd5', 'r2', 'x1', '_dil'], tags: [] },
  { id: 'becf-12011', material: 'carton', group: 'food-boxes', ecma: 'B15.06.00.53.B', fefco: '', variations: 0, dims: {a:190,b:160,c:75}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil'], tags: [], windows: true },
  { id: 'becf-12012', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {a:97.5,b:97.5,c:80}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-12013', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:100}, options: ['a', 'b', 'c', 'd', 'd5', 'e'], tags: [] },
  { id: 'becf-12014', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-12015', material: 'carton', group: 'food-boxes', ecma: 'B49.10.00.00 + lid', fefco: '', variations: 1, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'x', '_dil', '_dip', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12017', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'r', 'r2', 'x1', 'x2', 'x3', 'y1', 'y2', 'y3', '_flap'], tags: [] },
  { id: 'becf-12018', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {}, options: ['an1', 'an2', 'bfx1', 'bfx2', 'bfy1', 'gf1', 'gf1y1', 'gf2', 'gf2y1', 'gf2y2', 'gf3', 'gf3y1', 'gf4', 'gf4y1', 'h1', 'h2', 'l', 'slot1', 'slot2', 'slot3', 'slot4', 'tfy1', 'tfy2', 'v1', 'v2', 'w'], tags: [] },
  { id: 'becf-12019', material: 'carton', group: 'food-boxes', ecma: '', fefco: '', variations: 0, dims: {}, options: ['an1', 'cvrp', 'cvrx', 'cvry', 'gf', 'gfy', 'h1', 'h2', 'l', 'plh', 'plh1', 'pln', 'plr1', 'plw', 'plx1', 'r1', 'r2', 'r3', 'r4', 'r5', 'v1', 'v2', 'vent', 'vnt_h', 'vnt_r', 'vnt_x', 'vnt_y', 'w', 'winback', 'winfront', 'x1', 'x2', 'x3', 'x4', 'y1', 'y2'], tags: [] },
  { id: 'becf-12801', material: 'carton', group: 'polygonal-boxes', ecma: 'C10.40.55.20', fefco: '', variations: 0, dims: {a:100,c:150}, options: ['a', 'c', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12802', material: 'carton', group: 'polygonal-boxes', ecma: 'C10.40.20.20', fefco: '', variations: 0, dims: {a:100,c:150}, options: ['a', 'c', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-12803', material: 'carton', group: 'polygonal-boxes', ecma: 'C10.40.55.90', fefco: '', variations: 0, dims: {a:100,c:150}, options: ['a', 'c', 'd4', 'd5', '_dip', '_kulak'], tags: [] },
  { id: 'becf-12804', material: 'carton', group: 'polygonal-boxes', ecma: 'C10.10.20.20', fefco: '', variations: 0, dims: {a:200,b:110}, options: ['a', 'b', 'd4', 'd5', '_dil', '_kulak'], tags: [] },
  { id: 'becf-12805', material: 'carton', group: 'polygonal-boxes', ecma: 'D10.51.04.62', fefco: '', variations: 0, dims: {a:200,b:60,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil'], tags: [] },
  { id: 'becf-12806', material: 'carton', group: 'polygonal-boxes', ecma: 'D10.51.04.62', fefco: '', variations: 2, dims: {}, options: ['d', 'd1', 'gf', 'gf1', 'h', 'h1', 'l', 'v1', 'v2', 'wl'], tags: [] },
  { id: 'becf-11f01', material: 'carton', group: 'separators', ecma: 'F80.03.00.00', fefco: '', variations: 0, dims: {a:200,b:150,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-11f02', material: 'carton', group: 'separators', ecma: 'F80.03.00.00.B', fefco: '', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-11f03', material: 'carton', group: 'separators', ecma: 'F80.31.00.00', fefco: '', variations: 0, dims: {a:60,b:30,c:80}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-11f04', material: 'carton', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:0,b:150,c:20}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-11f05', material: 'carton', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:200,b:150,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i'], tags: [] },
  { id: 'becf-11f06', material: 'carton', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:200,b:150,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g'], tags: [] },
  { id: 'becf-11f07', material: 'carton', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:264,b:160,c:25}, options: ['a', 'b', 'c', 'd', 'd4', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 'r1'], tags: [] },
  { id: 'becf-11f08', material: 'carton', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'x1', 'y1'], tags: [] },
  { id: 'becf-11f09', material: 'carton', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:200,b:150,c:50}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5'], tags: [] },
  { id: 'becf-12401', material: 'carton', group: 'shirt-boxes', ecma: 'B31.21.00.00', fefco: '', variations: 0, dims: {a:200,b:120,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'x1', 'x2', 'y', 'y1', 'y2', '_dil', '_flap', '_kulak'], tags: [], windows: true },
  { id: 'becf-12402', material: 'carton', group: 'shirt-boxes', ecma: 'B30.02.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap'], tags: [] },
  { id: 'becf-12403', material: 'carton', group: 'shirt-boxes', ecma: 'B48.02.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', 'x', '_dil'], tags: [] },
  { id: 'becf-12404', material: 'carton', group: 'shirt-boxes', ecma: 'B30.02.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap'], tags: [] },
  { id: 'becf-12405', material: 'carton', group: 'shirt-boxes', ecma: 'B48.02.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', 'x', '_dil'], tags: [] },
  { id: 'becf-12406', material: 'carton', group: 'shirt-boxes', ecma: 'B48.02.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h', 'x', 'x1', '_dil', '_dip'], tags: [], windows: true },
  { id: 'becf-12407', material: 'carton', group: 'shirt-boxes', ecma: 'B48.02.00.00.B', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h', 'x', 'x1', '_dil', '_dip'], tags: [] },
  { id: 'becf-12408', material: 'carton', group: 'shirt-boxes', ecma: 'B14.05.00.00', fefco: '', variations: 1, dims: {a:150,b:80,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'x', '_dil', '_kulak'], tags: [], windows: true },
  { id: 'becf-1240a', material: 'carton', group: 'shirt-boxes', ecma: 'E40.82.00.00', fefco: '', variations: 0, dims: {a:140,b:90,c:35}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', '_kulak'], tags: [] },
  { id: 'becf-1240b', material: 'carton', group: 'shirt-boxes', ecma: '', fefco: '', variations: 0, dims: {a:160,b:75,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'y', 'y1', 'y2'], tags: [] },
  { id: 'becf-1240c', material: 'carton', group: 'shirt-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'x', 'x1', 'y', 'y1', 'y2', '_dil', '_kulak'], tags: [] },
  { id: 'becf-1240d', material: 'carton', group: 'shirt-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:90}, options: ['a', 'b', 'd4', 'd5'], tags: [] },
  { id: 'becf-1240e', material: 'carton', group: 'shirt-boxes', ecma: '', fefco: '', variations: 0, dims: {a:180,b:100,c:50}, options: ['a', 'b', 'c', 'd4', 'd5', 'x', '_dil', '_dip'], tags: [] },
  { id: 'becf-1240f', material: 'carton', group: 'shirt-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h', 'x1', 'x2', '_dil', '_dip'], tags: [] },
  { id: 'becf-12410', material: 'carton', group: 'shirt-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', 'x', '_dil', '_kulak'], tags: [] },
  { id: 'becf-10901', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.20.01.01', fefco: '', variations: 15, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'], windows: true },
  { id: 'becf-10911', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.01.01.00', fefco: '', variations: 0, dims: {a:200,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10912', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.40.01.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10913', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.45.01.01', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10914', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.46.01.03', fefco: '', variations: 2, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10915', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.20.01.01.32.33', fefco: '', variations: 1, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: ['dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10917', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.10.01.03.32', fefco: '', variations: 0, dims: {a:200,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-10918', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.10.01.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dip', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-10919', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.12.01.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dip', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-1091c', material: 'carton', group: 'snap-lock-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:80}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'k', 'r', 's', 'v1', '_dil', '_dip', '_flap', '_kulak'], tags: [] },
  { id: 'becf-1091d', material: 'carton', group: 'snap-lock-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'f', 'g', 'i', 'm', 'n', 'r2', 'r3', 'r4', 'r5', 's', 'x', 'y', 'z1', 'z2', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10a01', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.20.01.03', fefco: '', variations: 15, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10a11', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.20.01.01.35.41', fefco: '', variations: 0, dims: {a:100,b:100,c:55}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10b01', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.75.01.03', fefco: '', variations: 0, dims: {a:100,b:50,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10b03', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.75.01.03', fefco: '', variations: 0, dims: {a:200,b:50,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10b05', material: 'carton', group: 'snap-lock-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:100,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10c02', material: 'carton', group: 'snap-lock-boxes', ecma: '', fefco: '', variations: 647, dims: {}, options: [], tags: ['top_flap:friction_fit_tuck_in_flap', 'top_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'glue_flap:standard_flap', 'cover:standard_cover'] },
  { id: 'becf-10d01', material: 'carton', group: 'snap-lock-boxes', ecma: '', fefco: '', variations: 647, dims: {}, options: [], tags: ['top_flap:friction_fit_tuck_in_flap', 'top_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'glue_flap:standard_flap', 'cover:standard_cover'] },
  { id: 'becf-10e01', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.20.03.04.83', fefco: '', variations: 11, dims: {a:175,b:100,c:80}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-12e01', material: 'carton', group: 'snap-lock-boxes', ecma: 'A55.20.01.04.35.42', fefco: '', variations: 35, dims: {a:175,b:100,c:80}, options: ['a', 'b', 'c', 'd4', 'd5', 'f', 'g', 'j', 'k', 'o', 'p', 's', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-11e01', material: 'carton', group: 'special-boxes', ecma: 'F60.81.00.00', fefco: '', variations: 0, dims: {a:100,b:60}, options: ['a', 'b', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-11e02', material: 'carton', group: 'special-boxes', ecma: 'A10.20.03.03.32.51', fefco: '', variations: 11, dims: {a:155,b:100,c:160}, options: ['a', 'b', 'c', 'd4', 'd5', 'm', 'n', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-11e0e', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:140,b:60,c:110}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil', '_kulak'], tags: [] },
  { id: 'becf-11e0f', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:90,b:90,c:120}, options: ['a', 'b', 'c', 'd5', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11e10', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:120,b:100,c:60}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-11e11', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:145,b:145,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11e12', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:105,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', 'e', 'r'], tags: [] },
  { id: 'becf-11e13', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:90,b:90,c:120}, options: ['a', 'b', 'c', 'd4', 'd5', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11e14', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:75,c:85}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f'], tags: [] },
  { id: 'becf-11e15', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:35,c:5}, options: ['a', 'b', 'c', 'd5', 'r'], tags: [] },
  { id: 'becf-11e16', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:101,b:50,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'v1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11e17', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:80}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'r', 'x1', 'x2', 'y1', 'y2', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11e18', material: 'carton', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:140,b:100,c:60}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'g', 'x1', 'x2', 'y1'], tags: [] },
  { id: 'becf-11d01', material: 'carton', group: 'standard-boxes', ecma: 'A10.10.03.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-11d02', material: 'carton', group: 'standard-boxes', ecma: 'A12.12.01.01', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-11d03', material: 'carton', group: 'standard-boxes', ecma: 'A11.11.03.03.32', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-11d04', material: 'carton', group: 'standard-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'l', 'm', 'n', '_kulak'], tags: [] },
  { id: 'becf-11d05', material: 'carton', group: 'standard-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'l', 'm', 'n', '_kulak'], tags: [] },
  { id: 'becf-11d06', material: 'carton', group: 'standard-boxes', ecma: '', fefco: '', variations: 0, dims: {}, options: ['h', 'l', 'v1', 'v2', 'w', 'x1', 'x2', 'x3', 'x4', 'y1', 'y2', 'y3', 'y4', 'z1', '_flap', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-12701', material: 'carton', group: 'tags', ecma: 'F80.51.00.00', fefco: '', variations: 0, dims: {a:150,b:100}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'r', 'r1'], tags: [] },
  { id: 'becf-12702', material: 'carton', group: 'tags', ecma: 'F80.51.00.00', fefco: '', variations: 0, dims: {a:150,b:100}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r'], tags: [] },
  { id: 'becf-12703', material: 'carton', group: 'tags', ecma: 'F80.01.00.00', fefco: '', variations: 0, dims: {a:150,b:100}, options: ['a', 'b', 'd4', 'd5', 'r'], tags: [] },
  { id: 'becf-12704', material: 'carton', group: 'tags', ecma: 'F80.51.00.00', fefco: '', variations: 0, dims: {a:100}, options: ['a', 'b', 'c', 'd4'], tags: [] },
  { id: 'becf-12705', material: 'carton', group: 'tags', ecma: 'F80.51.00.00', fefco: '', variations: 0, dims: {a:100,b:50}, options: ['a', 'b', 'd', 'd4', 'd5', 'h'], tags: [] },
  { id: 'becf-12706', material: 'carton', group: 'tags', ecma: 'F80.52.00.00', fefco: '', variations: 0, dims: {a:100,b:100}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'r', 'r1'], tags: [] },
  { id: 'becf-11701', material: 'carton', group: 'tray-boxes', ecma: 'B20.01.00.53.B', fefco: '', variations: 2, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [], windows: true },
  { id: 'becf-11a01', material: 'carton', group: 'tray-boxes', ecma: 'B20.01.00.00', fefco: '', variations: 0, dims: {a:200,b:150,c:50}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-11a02', material: 'carton', group: 'tray-boxes', ecma: 'B40.22.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-11a03', material: 'carton', group: 'tray-boxes', ecma: 'B40.24.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_flap'], tags: [] },
  { id: 'becf-11a04', material: 'carton', group: 'tray-boxes', ecma: 'B20.02.00.00', fefco: '', variations: 0, dims: {a:150,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-11a05', material: 'carton', group: 'tray-boxes', ecma: 'B20.02.00.00.A', fefco: '', variations: 0, dims: {a:150,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_kulak'], tags: [], windows: true },
  { id: 'becf-11a06', material: 'carton', group: 'tray-boxes', ecma: 'B20.02.00.50', fefco: '', variations: 0, dims: {a:120,b:75,c:38}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'x1', 'x2', '_dil', '_kulak'], tags: [], windows: true },
  { id: 'becf-11a07', material: 'carton', group: 'tray-boxes', ecma: 'B40.20.00.00', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-11a08', material: 'carton', group: 'tray-boxes', ecma: 'B15.06.00.00.A', fefco: '', variations: 0, dims: {a:150,b:100,c:140}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-11a09', material: 'carton', group: 'tray-boxes', ecma: 'B40.20.82.50', fefco: '', variations: 0, dims: {a:150,b:90,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil', '_flap'], tags: [], windows: true },
  { id: 'becf-11a0a', material: 'carton', group: 'tray-boxes', ecma: 'B15.06.00.00.B', fefco: '', variations: 0, dims: {a:150,b:100,c:60}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [], windows: true },
  { id: 'becf-11a0b', material: 'carton', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:140,c:60}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-11a0c', material: 'carton', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:130,b:90,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h'], tags: [] },
  { id: 'becf-11a0d', material: 'carton', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:170,b:140,c:40}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-11a0e', material: 'carton', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:130,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-11a0f', material: 'carton', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'z1'], tags: [] },
  { id: 'becf-10101', material: 'carton', group: 'tuck-end-boxes', ecma: 'A20.20.03.01', fefco: '', variations: 47, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'], windows: true },
  { id: 'becf-10201', material: 'carton', group: 'tuck-end-boxes', ecma: 'A40.40.03.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 's', '_kulak'], tags: [] },
  { id: 'becf-10202', material: 'carton', group: 'tuck-end-boxes', ecma: 'A45.45.01.01', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 's', '_kulak'], tags: [] },
  { id: 'becf-10203', material: 'carton', group: 'tuck-end-boxes', ecma: 'A46.46.03.03', fefco: '', variations: 2, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 's', '_dil', '_kulak'], tags: [] },
  { id: 'becf-10204', material: 'carton', group: 'tuck-end-boxes', ecma: 'A20.20.01.01.32.33', fefco: '', variations: 1, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', '_dil', '_flap', '_kulak'], tags: ['dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10206', material: 'carton', group: 'tuck-end-boxes', ecma: 'A20.20.01.03', fefco: '', variations: 7, dims: {a:100,b:50,c:179.3}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10210', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 1, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'o', 'p', 'r1', 'r2', 'r3', 'r4', 's', 'w1', 'w2', '_dil', '_flap', '_kulak'], tags: ['dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10301', material: 'carton', group: 'tuck-end-boxes', ecma: 'A20.20.01.01', fefco: '', variations: 47, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10401', material: 'carton', group: 'tuck-end-boxes', ecma: 'A20.20.03.03', fefco: '', variations: 47, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10501', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 11, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'f', 'g', 'i', 'o', 'p', 'r1', 's', 'z1', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10601', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 35, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd3', 'd4', 'd5', 'v1', 'v11', 'v2', 'w1', 'w2', 'w3', 'w4', 'w6', 'z1', 'z2', 'z4', 'z5'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:full_angled_dust_flap'] },
  { id: 'becf-10701', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 47, dims: {}, options: ['h', 'l', 'v1', 'v2', 'v3', 'v4', 'v5', 'w', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-10803', material: 'carton', group: 'tuck-end-boxes', ecma: 'A20.20.01.03', fefco: '', variations: 5831, dims: {}, options: [], tags: ['top_flap:uni_tuck_flap', 'bottom_flap:uni_tuck_flap', 'top_tuck:sit_lock_tuck', 'bottom_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'bottom_dust_flap:slit_lock_dust_flap', 'glue_flap:standard_flap', 'cover:standard_cover'] },
  { id: 'becf-1082d93', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 5831, dims: {}, options: [], tags: ['top_flap:uni_tuck_flap', 'bottom_flap:uni_tuck_flap', 'top_tuck:sit_lock_tuck', 'bottom_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'bottom_dust_flap:slit_lock_dust_flap', 'glue_flap:flap_with_separator', 'cover:standard_cover'] },
  { id: 'becf-10838f7', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 5831, dims: {}, options: [], tags: ['top_flap:uni_tuck_flap', 'bottom_flap:uni_tuck_flap', 'top_tuck:sit_lock_tuck', 'bottom_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'bottom_dust_flap:slit_lock_dust_flap', 'glue_flap:flap_with_separator', 'cover:standard_cover', 'hanger:standard_hanger', 'hang_hole:standard_euro'] },
  { id: 'becf-1085b23', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 5831, dims: {}, options: [], tags: ['top_flap:uni_tuck_flap', 'bottom_flap:uni_tuck_flap', 'top_tuck:sit_lock_tuck', 'bottom_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'bottom_dust_flap:slit_lock_dust_flap', 'glue_flap:flap_with_lock', 'cover:standard_cover'] },
  { id: 'becf-1086687', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 5831, dims: {}, options: [], tags: ['top_flap:uni_tuck_flap', 'bottom_flap:uni_tuck_flap', 'top_tuck:sit_lock_tuck', 'bottom_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'bottom_dust_flap:slit_lock_dust_flap', 'glue_flap:flap_with_lock', 'cover:standard_cover', 'hanger:standard_hanger', 'hang_hole:standard_euro'] },
  { id: 'becf-108b67', material: 'carton', group: 'tuck-end-boxes', ecma: '', fefco: '', variations: 5831, dims: {}, options: [], tags: ['top_flap:uni_tuck_flap', 'bottom_flap:uni_tuck_flap', 'top_tuck:sit_lock_tuck', 'bottom_tuck:sit_lock_tuck', 'top_dust_flap:slit_lock_dust_flap', 'bottom_dust_flap:slit_lock_dust_flap', 'glue_flap:standard_flap', 'cover:standard_cover', 'hanger:standard_hanger', 'hang_hole:standard_euro'] },
  { id: 'becf-10b02', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.75.00.03', fefco: '', variations: 0, dims: {a:100,b:50,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'v1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-10b04', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.75.00.03', fefco: '', variations: 0, dims: {a:200,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'v1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11001', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.20.00.01', fefco: '', variations: 15, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', 'v1', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'], windows: true },
  { id: 'becf-11011', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.01.00.00', fefco: '', variations: 0, dims: {a:200,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11012', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.40.00.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11013', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.45.00.01', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11014', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.46.00.01', fefco: '', variations: 2, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-11015', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.20.00.01.32.33', fefco: '', variations: 1, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dil', '_dip', '_flap', '_kulak'], tags: ['dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-11017', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.10.00.03.32', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dil', '_dip', '_flap', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-11018', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.10.00.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dip', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-11019', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.12.00.03', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'v1', '_dip', '_kulak'], tags: ['dust_flap:full_angled_dust_flap'] },
  { id: 'becf-1101c', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.20.00.01.32.33', fefco: '', variations: 1, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'r1', 'r2', 'r3', 'r4', 'v1', 'w1', 'w2', '_dil', '_dip', '_flap', '_kulak'], tags: ['dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-11101', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.20.00.03', fefco: '', variations: 15, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'o', 'p', 's', 'v1', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-12d01', material: 'carton', group: 'tuck-top-auto-bottom-boxes', ecma: 'A60.20.00.04.35.42', fefco: '', variations: 35, dims: {a:175,b:100,c:80}, options: ['a', 'b', 'c', 'd4', 'd5', 'f', 'g', 'j', 'k', 'o', 'p', 's', 'v1', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-12501', material: 'carton', group: 'wrap-around-labels', ecma: 'F70.62.00.00', fefco: '', variations: 0, dims: {a:200,b:150,c:225}, options: ['a', 'b', 'c', 'd5'], tags: [] },
  { id: 'becf-12502', material: 'carton', group: 'wrap-around-labels', ecma: '', fefco: '', variations: 0, dims: {a:150,b:50,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'k', 'x1', 'y1', 'z1', '_dil'], tags: [] },
  { id: 'becf-12503', material: 'carton', group: 'wrap-around-labels', ecma: '', fefco: '', variations: 0, dims: {a:100,b:80,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', '_kulak'], tags: [] },
  { id: 'becf-12504', material: 'carton', group: 'wrap-around-labels', ecma: '', fefco: '', variations: 0, dims: {a:450,b:335}, options: ['a', 'b', 'd', 'r', 'v1', 'v2', 'w1', 'x', 'x1', 'x2', 'y', 'y1'], tags: [] },
  { id: 'becf-21f01', material: 'corrugated', group: 'separators', ecma: '', fefco: '0930', variations: 0, dims: {a:40,b:40,c:100}, options: ['a', 'b', 'c', 'd', 'd4', 'e'], tags: [] },
  { id: 'becf-21f02', material: 'corrugated', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:200,b:150,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i'], tags: [] },
  { id: 'becf-21f03', material: 'corrugated', group: 'separators', ecma: '', fefco: '0458', variations: 0, dims: {a:200,b:150,c:70}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-21f04', material: 'corrugated', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:200,b:150,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h'], tags: [] },
  { id: 'becf-21f05', material: 'corrugated', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:150,b:75,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-21f06', material: 'corrugated', group: 'separators', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-20901', material: 'corrugated', group: 'snap-lock-boxes', ecma: '', fefco: '0215', variations: 23, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-20a01', material: 'corrugated', group: 'snap-lock-boxes', ecma: '', fefco: '0215', variations: 35, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-20d01', material: 'corrugated', group: 'snap-lock-boxes', ecma: '', fefco: '', variations: 0, dims: {a:250,b:150,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-21d08', material: 'corrugated', group: 'snap-lock-boxes', ecma: '', fefco: '0216', variations: 1, dims: {}, options: ['h', 'l', 'v1', 'v2', 'w', '_dip', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-21e04', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:260,b:180,c:95}, options: ['a', 'b', 'c', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-21e05', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:260,b:180,c:95}, options: ['a', 'b', 'c', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-21e06', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:260,b:180,c:95}, options: ['a', 'b', 'c', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-21e07', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '0207', variations: 23, dims: {a:200,b:140,c:100}, options: ['a', 'b', 'c', 'd4', 'd5', 'f', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-21e1f', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '0217', variations: 1, dims: {a:250,b:150,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-21e20', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 1, dims: {a:250,b:150,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-21e21', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '0717', variations: 0, dims: {a:180,b:121.2,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', '_dip', '_kulak'], tags: [] },
  { id: 'becf-21e22', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:3,b:2,c:20}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h'], tags: [] },
  { id: 'becf-21e23', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:20,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'f', 'g', 'i', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-21e24', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', 'm', 'n', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-21e25', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:160,c:90}, options: ['a', 'b', 'c', 'd', 'd1', 'd10', 'd2', 'd3', 'd5', 'e', 'x1', 'x2', 'y1', 'y2', 'z', 'z1', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-21e26', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:200,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'x1', 'y1', 'y2', '_dip', '_kulak'], tags: [] },
  { id: 'becf-21e29', material: 'corrugated', group: 'special-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:160,c:90}, options: ['a', 'b', 'c', 'd', 'd1', 'd10', 'd2', 'd3', 'd5', 'e', 'plx1', 'plx2', 'x1', 'y1', 'z', 'z1', 'z2', '_dil', '_flap', '_kulak'], tags: [] },
  { id: 'becf-21d01', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0201', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-21d02', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-21d03', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0203', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-21d04', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0201', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-21d05', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-21d06', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0203', variations: 0, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-21d07', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '', variations: 0, dims: {a:250,b:100,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', '_dil', '_kulak'], tags: [] },
  { id: 'becf-21d0a', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0201', variations: 0, dims: {}, options: ['h', 'l', 'v1', 'v2', 'w', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-21e01', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0225', variations: 0, dims: {a:100,b:80,c:75}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_kulak'], tags: [] },
  { id: 'becf-21e02', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0471', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-21e03', material: 'corrugated', group: 'standard-boxes', ecma: '', fefco: '0470', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil'], tags: [] },
  { id: 'becf-21701', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0427', variations: 5, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'ubent', 'v1', 'v2', '_flap'], tags: [] },
  { id: 'becf-21704', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0426', variations: 0, dims: {a:150,b:200,c:50}, options: ['a', 'b', 'c', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-21705', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0426', variations: 0, dims: {a:150,b:200,c:50}, options: ['a', 'b', 'c', 'd4', 'd5', 'e'], tags: [] },
  { id: 'becf-21707', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0427', variations: 2, dims: {a:160,b:100,c:70}, options: ['a', 'b', 'c', 'ubent', 'v1', 'v2', 'y2', 'y3', 'z2', 'z3', 'z4', '_flap'], tags: [] },
  { id: 'becf-2170a', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0421', variations: 2, dims: {a:100,b:100,c:50}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap'], tags: [] },
  { id: 'becf-21711', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:200,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'r1', 'r2', 'r3'], tags: [] },
  { id: 'becf-21712', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 2, dims: {}, options: ['h', 'l', 'v1', 'v2', 'w', 'x1', 'y1', 'y2', 'z', 'z1', 'z2'], tags: [] },
  { id: 'becf-21a01', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0422', variations: 0, dims: {a:100,b:100,c:50}, options: ['a', 'b', 'c', 'd4', 'd5'], tags: [] },
  { id: 'becf-21a02', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:80}, options: ['a', 'b', 'c', 'd4', 'd5', 'g', 'h'], tags: [] },
  { id: 'becf-21b01', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0330', variations: 0, dims: {a:300,b:200,c:100}, options: ['a', 'b', 'c', 'd4', 'd5', 'h', 'v10', 'v11'], tags: [] },
  { id: 'becf-21b02', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0330', variations: 0, dims: {a:300,b:200,c:100}, options: ['a', 'b', 'c', 'd4', 'd5', 'h', 'v10', 'v11'], tags: [] },
  { id: 'becf-21b03', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0425', variations: 0, dims: {a:300,b:250,c:80}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_dil'], tags: [] },
  { id: 'becf-21b04', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-21b05', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:160,b:100,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'r1', 'r2', '_dil'], tags: [] },
  { id: 'becf-21b06', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:195,b:145,c:55}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g'], tags: [] },
  { id: 'becf-21b07', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:160,b:100,c:70}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g'], tags: [] },
  { id: 'becf-21c01', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0451', variations: 0, dims: {a:200,b:100,c:40}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-21c02', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0300', variations: 0, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_flap', '_kulak'], tags: [] },
  { id: 'becf-21c03', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0761', variations: 0, dims: {a:200,b:185,c:85}, options: ['a', 'b', 'c', 'd', 'd4', 'd5'], tags: [] },
  { id: 'becf-21c04', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0300-A', variations: 0, dims: {a:150,b:120,c:80}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'r', 'r1'], tags: [] },
  { id: 'becf-21c05', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0400', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'r', 'r1', 'x1'], tags: [] },
  { id: 'becf-21c06', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0401', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'r1'], tags: [] },
  { id: 'becf-21c07', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0403', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'r1'], tags: [] },
  { id: 'becf-21c08', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0404', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'r1'], tags: [] },
  { id: 'becf-21c09', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0405', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'r', 'r1'], tags: [] },
  { id: 'becf-21c0a', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '', variations: 0, dims: {a:300,b:200,c:60}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'x1', 'y1', 'y2'], tags: [] },
  { id: 'becf-21c0b', material: 'corrugated', group: 'tray-boxes', ecma: '', fefco: '0301', variations: 0, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', '_flap', '_kulak'], tags: [] },
  { id: 'becf-20101', material: 'corrugated', group: 'tuck-end-boxes', ecma: '', fefco: '0211', variations: 71, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-20301', material: 'corrugated', group: 'tuck-end-boxes', ecma: '', fefco: '0210', variations: 71, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-20401', material: 'corrugated', group: 'tuck-end-boxes', ecma: '', fefco: '0210', variations: 71, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-21001', material: 'corrugated', group: 'tuck-top-auto-bottom-boxes', ecma: '', fefco: '0713', variations: 23, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-21101', material: 'corrugated', group: 'tuck-top-auto-bottom-boxes', ecma: '', fefco: '0713', variations: 23, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd4', 'd5', '_dil', '_dip', '_flap', '_kulak'], tags: ['flap:uni_tuck_flap', 'tuck:sit_lock_tuck', 'dust_flap:slit_lock_dust_flap'] },
  { id: 'becf-21401', material: 'corrugated', group: 'tuck-top-auto-bottom-boxes', ecma: '', fefco: '', variations: 0, dims: {a:250,b:150,c:200}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', '_dil', '_dip', '_kulak'], tags: [] },
  { id: 'becf-30301', material: 'hardboard', group: 'binders', ecma: '', fefco: '', variations: 0, dims: {a:230,b:100,c:320}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h'], tags: [] },
  { id: 'becf-30203', material: 'hardboard', group: 'boxes-with-hinged-lid', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'e', 'f', 'h', 'm', 'x1', 'x2', 'y1', 'y2', 'y3', 'z1', 'z2'], tags: [] },
  { id: 'becf-30205', material: 'hardboard', group: 'boxes-with-hinged-lid', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', '_kulak'], tags: [] },
  { id: 'becf-30206', material: 'hardboard', group: 'boxes-with-hinged-lid', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'], tags: [] },
  { id: 'becf-30207', material: 'hardboard', group: 'boxes-with-hinged-lid', ecma: '', fefco: '', variations: 2, dims: {a:300,b:200,c:75}, options: ['a', 'b', 'c', 'd', 'd1', 'd4', 'd5', 'e', 'f', 'x1', 'x2', 'x3', 'y1', 'y2'], tags: [] },
  { id: 'becf-3020a', material: 'hardboard', group: 'boxes-with-hinged-lid', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd4', 'd5', 'e', 'f', 'h', 'x1', 'x2', 'x3', 'y1', 'y2'], tags: [] },
  { id: 'becf-3020b', material: 'hardboard', group: 'boxes-with-hinged-lid', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'h', 'x1', 'x2', 'y1', 'y2'], tags: [] },
  { id: 'becf-30101', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 2, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'x1', 'x2', 'y1', 'y2'], tags: [] },
  { id: 'becf-30102', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 2, dims: {a:100,b:50,c:150}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h', '_kulak'], tags: [] },
  { id: 'becf-30103', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 0, dims: {a:150,b:100,c:75}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'x1', 'x2', 'x3', 'y1', 'y2', 'y3', 'z', 'z1', 'z2', 'z3', 'z4', 'z5'], tags: [] },
  { id: 'becf-30104', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'x1', 'y1', '_kulak'], tags: [] },
  { id: 'becf-30105', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 0, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'h', 'x1', 'y1', '_kulak'], tags: [] },
  { id: 'becf-30109', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 0, dims: {a:100,b:90,c:30}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'x1', 'x2', 'x3', 'y1', 'y2', 'y3'], tags: [] },
  { id: 'becf-3010a', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 1, dims: {a:150,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'k'], tags: [] },
  { id: 'becf-3010e', material: 'hardboard', group: 'covered-solid-board-boxes', ecma: '', fefco: '', variations: 1, dims: {a:200,b:100,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'g', 'h', 'k', 'x1', 'x2', 'y1', 'y2'], tags: [] },
  { id: 'becf-30701', material: 'hardboard', group: 'display-materials', ecma: '', fefco: '', variations: 1, dims: {a:1000,b:700}, options: ['a', 'b', 'd4', 'd5'], tags: [] },
  { id: 'becf-30702', material: 'hardboard', group: 'display-materials', ecma: '', fefco: '', variations: 0, dims: {a:300,b:300,c:50}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'e', 'f', 'r', 'x1', 'x2', 'y1'], tags: [], windows: true },
  { id: 'becf-30600', material: 'hardboard', group: 'swatch-cards', ecma: '', fefco: '', variations: 0, dims: {a:295,b:115}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h'], tags: [] },
  { id: 'becf-30602', material: 'hardboard', group: 'swatch-cards', ecma: '', fefco: '', variations: 0, dims: {a:295,b:115,c:25}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h'], tags: [] },
  { id: 'becf-30603', material: 'hardboard', group: 'swatch-cards', ecma: '', fefco: '', variations: 0, dims: {a:295,b:115,c:20}, options: ['a', 'b', 'c', 'd', 'd4', 'd5', 'h'], tags: [] },
]

export const DCT_GROUPS: readonly { material: MaterialKind; group: TemplateCategory; count: number }[] = [
  { material: 'carton', group: 'angled-boxes', count: 3 },
  { material: 'carton', group: 'carton-bags-pillows', count: 14 },
  { material: 'carton', group: 'envelopes', count: 5 },
  { material: 'carton', group: 'folders', count: 13 },
  { material: 'carton', group: 'food-boxes', count: 24 },
  { material: 'carton', group: 'polygonal-boxes', count: 6 },
  { material: 'carton', group: 'separators', count: 9 },
  { material: 'carton', group: 'shirt-boxes', count: 15 },
  { material: 'carton', group: 'snap-lock-boxes', count: 20 },
  { material: 'carton', group: 'special-boxes', count: 13 },
  { material: 'carton', group: 'standard-boxes', count: 6 },
  { material: 'carton', group: 'tags', count: 6 },
  { material: 'carton', group: 'tray-boxes', count: 16 },
  { material: 'carton', group: 'tuck-end-boxes', count: 18 },
  { material: 'carton', group: 'tuck-top-auto-bottom-boxes', count: 14 },
  { material: 'carton', group: 'wrap-around-labels', count: 4 },
  { material: 'corrugated', group: 'separators', count: 6 },
  { material: 'corrugated', group: 'snap-lock-boxes', count: 4 },
  { material: 'corrugated', group: 'special-boxes', count: 13 },
  { material: 'corrugated', group: 'standard-boxes', count: 11 },
  { material: 'corrugated', group: 'tray-boxes', count: 27 },
  { material: 'corrugated', group: 'tuck-end-boxes', count: 3 },
  { material: 'corrugated', group: 'tuck-top-auto-bottom-boxes', count: 3 },
  { material: 'hardboard', group: 'binders', count: 1 },
  { material: 'hardboard', group: 'boxes-with-hinged-lid', count: 6 },
  { material: 'hardboard', group: 'covered-solid-board-boxes', count: 8 },
  { material: 'hardboard', group: 'display-materials', count: 2 },
  { material: 'hardboard', group: 'swatch-cards', count: 3 },
]
